name: angular_app
description: A web app that uses AngularDart
version: 0.0.1

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular2: ^3.1.0

dev_dependencies:
  dart_to_js_script_rewriter: ^1.0.1
  browser: ^0.10.0

transformers:
- angular2:
    entry_points: web/main.dart
- angular2/transform/reflection_remover:
    $include: test/**_test.dart
- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc
